new_tab("https://admin.hotfrog.de/dashboard")
wait_for_load()
js("new Promise(function(r){setTimeout(r,2000);})")
print("URL:", page_info().get("url"))
print("TEXT:", js("document.body.innerText.replace(/\\n+/g,' | ').slice(0,500)"))
print("SHOT:", capture_screenshot())